apiVersion: v1
kind: Pod
metadata:
  name: client-user10003
  namespace: default
  annotations:
    nri.io/kerberos-auth: "enabled"
    nri.io/kerberos-uid: "10003"
    nri.io/kerberos-gid: "5003"
    nri.io/kerberos-fsid: "5003"
    nri.io/kerberos-scenario: "no sidecar"
spec:
  securityContext:
    runAsUser: 10003
    runAsGroup: 5003
    fsGroup: 5003
  containers:
  # Main NFS client container
  - name: nfs-client
    image: nfs-kerberos-client:latest
    imagePullPolicy: Never
    securityContext:
      runAsUser: 10003
      runAsGroup: 5003
    env:
    - name: KRB5CCNAME
      value: "FILE:/tmp/krb5cc_10003"
    - name: KERBEROS_USER
      value: "user10003"
    - name: KERBEROS_REALM
      valueFrom:
        configMapKeyRef:
          name: service-hostnames
          key: KERBEROS_REALM
    - name: KDC_HOSTNAME
      valueFrom:
        configMapKeyRef:
          name: service-hostnames
          key: KDC_HOSTNAME
    - name: NFS_HOSTNAME
      valueFrom:
        configMapKeyRef:
          name: service-hostnames
          key: NFS_HOSTNAME
    - name: KERBEROS_RENEWAL_TIME
      value: "300"
    - name: NFS_WRITE_INTERVAL
      value: "120"
    volumeMounts:
    - name: nfs-home
      mountPath: /home
    - name: keytabs
      mountPath: /etc/keytabs
      readOnly: true
    - name: krb5-config
      mountPath: /etc/krb5.conf
      readOnly: true
    - name: ccache
      mountPath: /tmp
  volumes:
  - name: nfs-home
    persistentVolumeClaim:
      claimName: nfs-user10003
  - name: keytabs
    hostPath:
      path: /etc/keytabs
      type: Directory
  - name: krb5-config
    hostPath:
      path: /etc/krb5.conf
      type: File
  - name: ccache
    hostPath:
      path: /tmp
      type: Directory
  restartPolicy: Always
