apiVersion: v1
kind: Pod
metadata:
  name: client-user10005
  namespace: default
  annotations:
    nri.io/kerberos-auth: "enabled"
    nri.io/kerberos-uid: "10005"
    nri.io/kerberos-gid: "5005"
    nri.io/kerberos-fsid: "5005"
    nri.io/kerberos-scenario: "nothing about nfs in client, 8 minute refresh"
spec:
  securityContext:
    runAsUser: 10005
    runAsGroup: 5005
    fsGroup: 5005
  containers:
  # Kerberos sidecar for credential management
  - name: krb5-sidecar
    image: krb5-sidecar:latest
    securityContext:
      runAsUser: 10005
      runAsGroup: 5005
    imagePullPolicy: Never
    env:
    - name: KRB5CCNAME
      value: "FILE:/tmp/krb5cc_10005"
    - name: KERBEROS_USER
      value: "user10005"
    - name: KERBEROS_REALM
      valueFrom:
        configMapKeyRef:
          name: service-hostnames
          key: KERBEROS_REALM
    - name: KDC_HOSTNAME
      valueFrom:
        configMapKeyRef:
          name: service-hostnames
          key: KDC_HOSTNAME
    - name: NFS_HOSTNAME
      valueFrom:
        configMapKeyRef:
          name: service-hostnames
          key: NFS_HOSTNAME
    - name: KERBEROS_RENEWAL_TIME
      value: "480"  # 8 min for testing
    volumeMounts:
    - name: keytabs
      mountPath: /etc/keytabs
      readOnly: true
    - name: krb5-config
      mountPath: /etc/krb5.conf
      readOnly: true
    - name: ccache
      mountPath: /tmp
    lifecycle:
      preStop:
        exec:
          command: ["/usr/bin/kdestroy"]
  # Main NFS client container
  - name: nfs-client
    image: nfs-kerberos-client:latest
    securityContext:
      runAsUser: 10005
      runAsGroup: 5005
    imagePullPolicy: Never
    command: ["/usr/local/bin/entrypoint.sh"]
    volumeMounts:
    - name: nfs-home
      mountPath: /home
    env:
    - name: NFS_WRITE_INTERVAL
      value: "240"
  volumes:
  - name: nfs-home
    persistentVolumeClaim:
      claimName: nfs-user10005
  - name: keytabs
    hostPath:
      path: /etc/keytabs
      type: Directory
  - name: krb5-config
    hostPath:
      path: /etc/krb5.conf
      type: File
  - name: ccache
    hostPath:
      path: /tmp
      type: Directory
  restartPolicy: Always
