apiVersion: v1
kind: Pod
metadata:
  name: client-user10004-kcm
  namespace: default
spec:
  hostAliases:
  - ip: "10.1.0.25"
    hostnames:
    - "kdc.example.com"
    - "nfs.example.com"
  securityContext:
    runAsUser: 10004
    runAsGroup: 5004
    fsGroup: 5004
  containers:
  # Kerberos sidecar for credential management
  - name: krb5-sidecar
    image: krb5-sidecar:latest
    imagePullPolicy: Never
    env:
    - name: KRB5CCNAME
      value: "KCM:"
    - name: KERBEROS_USER
      value: "user10004"
    - name: KERBEROS_REALM
      value: "EXAMPLE.COM"
    - name: KERBEROS_RENEWAL_TIME
      value: "3600"  # 1 hour for testing
    volumeMounts:
    - name: keytabs
      mountPath: /etc/keytabs
      readOnly: true
    - name: krb5-config
      mountPath: /etc/krb5.conf
      readOnly: true
    - name: kcm-socket
      mountPath: /var/run/.heim_org.h5l.kcm-socket
    - name: rpc-pipefs
      mountPath: /var/lib/nfs/rpc_pipefs
    lifecycle:
      preStop:
        exec:
          command: ["/usr/bin/kdestroy"]
  # Main NFS client container
  - name: nfs-client
    image: nfs-kerberos-client:latest
    imagePullPolicy: Never
    securityContext:
      runAsUser: 10004
      runAsGroup: 5004
    env:
    - name: KRB5CCNAME
      value: "KCM:"
    - name: KERBEROS_USER
      value: "user10004"
    - name: KERBEROS_REALM
      value: "EXAMPLE.COM"
    command: ["/bin/bash", "-c"]
    args:
      - |
        echo "Starting NFS client container with KCM..."
        echo "Waiting for sidecar to authenticate..."
        sleep 10
        echo "Checking KCM credentials..."
        export KRB5CCNAME=KCM:
        klist || echo "No credentials yet"
        echo "Testing NFS access..."
        ls -la /home/ && echo "SUCCESS: Can list NFS directory" || echo "Cannot access NFS directory"
        echo "Testing NFS write..."
        echo "KCM Test: Written by user10004 at $(date)" > /home/kcm-test.txt && echo "SUCCESS: Can write to NFS" || echo "Cannot write to NFS"
        echo "Container ready. Keeping alive..."
        while true; do sleep 30; done
    volumeMounts:
    - name: nfs-home
      mountPath: /home
    - name: krb5-config
      mountPath: /etc/krb5.conf
      readOnly: true
    - name: kcm-socket
      mountPath: /var/run/.heim_org.h5l.kcm-socket
    - name: rpc-pipefs
      mountPath: /var/lib/nfs/rpc_pipefs
  volumes:
  - name: nfs-home
    persistentVolumeClaim:
      claimName: nfs-user10004
  - name: keytabs
    hostPath:
      path: /etc/keytabs
      type: Directory
  - name: krb5-config
    hostPath:
      path: /etc/krb5.conf
      type: File
  - name: kcm-socket
    hostPath:
      path: /var/run/.heim_org.h5l.kcm-socket
      type: Socket
  - name: rpc-pipefs
    hostPath:
      path: /var/lib/nfs/rpc_pipefs
      type: Directory
  restartPolicy: Always
