apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-user10002
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-krb5
  volumeName: nfs-pv-user10002